### ISSUE TITLE
Allow installing all locked dev-dependencies easily into a tox env

### ISSUE THREAD

**Issue by johnthagen** [enpaul/tox-poetry-installer#14]
The way many of the projects I work on are setup with tox env's is to specify and lock all dev-dependencies, and then install them into each `tox` environment that is used for development.

From the `pip-tools` world, this looks like this:

- https://github.com/johnthagen/python-blueprint/blob/master/dev-requirements.txt
- https://github.com/johnthagen/python-blueprint/blob/4915045695df6aae3919aec8450081cc6f5c5a2e/tox.ini#L57

What I find useful about this work flow, is that I don't have to repeat the `deps` for every single `tox` `testenv`. This does have the downside of installing extra dependencies into certain `testenv`s, but for development `testenv`s, my teams have found that reducing the duplication and simplifying the process is worth it.

The feature I would like to offer for consideration is being to specify that I would like to optionally install all of the `[tool.poetry.dev-dependencies]` installed into a `testenv`.

So that instead of:

```ini
[testenv]
description = Run the tests
require_locked_deps = true
deps =
    pytest
    pytest-cov
    black
    pylint
    mypy
commands = ...
```

Where all of the `deps` are duplicated in the `testenv` and `pyproject.toml`, it was possible to instead write:

```ini
[testenv]
description = Run the tests
require_locked_deps = true
install_poetry_dev_dependencies = true
commands = ...
```

Note, this is similar to https://github.com/sinoroc/tox-poetry-dev-dependencies, but `tox-poetry-installer` also supports a wider existing feature set.

**Comment by enpaul** [comment]
Thanks for the feature suggestion! On principle I'm not opposed to adding this, but as you note the tox-poetry-dev-dependencies plugin already has this functionality. Is there a reason why this plugin and the tox-poetry-dev-dependencies plugin couldn't be used in tandem to support both feature sets?

**Comment by johnthagen** [comment]
> Is there a reason why this plugin and the tox-poetry-dev-dependencies plugin couldn't be used in tandem to support both feature sets?

The main issue I'm running into is that poetry >= 1.1.0 lockfile sytax is not supported in all cases yet: https://github.com/sinoroc/tox-poetry-dev-dependencies/issues/48 so we can't actually use the lockfile with our projects, only reading from `pyproject.toml` to get the `dev-dependencies`. But it seems like one option is to wait for `poetry-core` to mature some more so that plugins don't need to duplicate this logic.

And at a higher level, integration with `tox` has been the biggest sticking point with trying to migrate to `poetry`. Ideally, as things mature projects would only need to depend on one plugin, rather than 2 if possible and then the community could rally behind supporting a single package.

**Comment by enpaul** [comment]
Makes sense to me! I'll add this to the planned feature list
