### ISSUE TITLE
Add a Changelog

### ISSUE THREAD

**Issue by johnthagen** [enpaul/tox-poetry-installer#36]
It would be very helpful if there was a changelog that noted the various fixes and changes for the past few releases and new ones going forward.

Thanks!

**Comment by enpaul** [comment]
Good suggestion @johnthagen! I try to document the changes made in each release in the [github releases](https://github.com/enpaul/tox-poetry-installer/releases) themselves, but I know that can be a pain to parse. I'll work on putting together a dedicated changelog file.

**Comment by johnthagen** [comment]
Ah, I had forgotten about the GitHub releases section. Yeah, perhaps that content could be mirrored into a `CHANGELOG.md` in the repo or similar.
