### ISSUE TITLE
0.6.4 breaks Python 3.10 compatibility

### ISSUE THREAD

**Issue by brechtm** [enpaul/tox-poetry-installer#45]
Since upgrading tox-poetry-installer to 0.6.4, my Python 3.10 runs started failing:

- 0.6.2 good: https://github.com/brechtm/rinohtype/runs/2021425595?check_suite_focus=true
- 0.6.4 bad: https://github.com/brechtm/rinohtype/runs/2020577839?check_suite_focus=true

I've tested locally with 0.6.3 and that version works fine.

From the logs, it's not immediately obvious to me what the issue is.

**Comment by enpaul** [comment]
@brechtm Can you share the exact version of 3.10 you're using for that run? Since it's still in alpha I want to make sure I can replicate it exactly.

This may also be an issue with an upstream, possibly pip or poetry. If you have a moment could you try running tox locally in a poetry environment that uses the same release of 3.10 as the run? I can also work on running that same test.

**Comment by brechtm** [comment]
The version is listed in that build log, under "Install Python 3.10.0-alpha - 3.10": 3.10.0-alpha.5.

**Comment by brechtm** [comment]
Locally, I tried with 3.10-dev installed today using pyenv (`python3.10 --version` reports _3.10.0a6+_). This fails with a different error:
```
...
unit-py310 run-test: commands[0] | python run_tests.py tests
[79468] /Users/brechtm/Documents/Code/rinohtype$ /Users/brechtm/Documents/Code/rinohtype/.tox/unit-py310/bin/python run_tests.py tests
ERROR: usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: -n
  inifile: /Users/brechtm/Documents/Code/rinohtype/setup.cfg
  rootdir: /Users/brechtm/Documents/Code/rinohtype

ERROR: InvocationError for command /Users/brechtm/Documents/Code/rinohtype/.tox/unit-py310/bin/python run_tests.py tests (exited with code 4)
```

0.6.3 show no issues executing the same test environment.

I'm migrating from tox to nox (but certainly not because of tox-poetry-installer!), so I won't be putting more time into investigating this issue I'm afraid.

**Comment by enpaul** [comment]
Excellent, thank you for the additional diagnostic info! I'll work on taking a look at this, I suspect it might be due to an upstream library but I need to confirm that. Thanks for reporting the bug!

**Comment by enpaul** [comment]
Given that I can't repro this anymore using 0.8.x I'm going to close this issue
