### ISSUE TITLE
ModuleNotFoundError: No module named 'poetry.core'

### ISSUE THREAD

**Issue by jedie** [enpaul/tox-poetry-installer#66]
e.g.: https://github.com/jedie/django-tools/runs/4278961704?check_suite_focus=true

**Comment by enpaul** [comment]
Hi @jedie, thanks for using this project! It looks like you're using an older version of tox-poetry-installer [here](https://github.com/jedie/django-tools/runs/4278961704?check_suite_focus=true#step:5:208). Could you try updating to the latest version and see if that pipeline still encounters this problem?

**Comment by jedie** [comment]
Sorry, i removed "tox-gh-actions" from my project and use "tox-poetry" ... this works fine...

Maybe the trouble was a result of the support of python 3.6 ?!? See: https://github.com/jedie/django-tools/compare/v0.48.3...v0.49.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711L38

**Comment by enpaul** [comment]
Very sorry this plugin wasn't able to help you with your project. I'm unable to view the link you posted (github says there's nothing to compare), but if you end up giving `tox-poetry-installer` a try again in the future and still run into problems then please let me know.
