### ISSUE TITLE
Private repository with credentials

### ISSUE THREAD

**Issue by aha79** [enpaul/tox-poetry-installer#71]
I have a poetry project with packages from a private repository. With poetry alone it works as expected, but tox-poetry-installer emits the warning

"WARNING: tox-poetry-installer: Skipping XXXX: no locked version found compatible with target python version 3.7.9"

for the packages XXXX in the private repo.

Despite what it says it seems not to be a problem with the python version. The warning is shown for different versions of python, (and where poetry  has no issue installing the package).

Could it be that a custom repository (e.g. with 'secondary=true') with credentials is not (yet) supported by `tox-poetry-installer` ?

Specifically I have

```
[[tool.poetry.source]]
name = "custom_repo"
url = "https://XXXXXXXXXXXX/packages/pypi/simple"
secondary = true
```

Which I configured once with 

`poetry config http-basic.custom_repo username password`

As a workaround I tried setting 
```
[testenv]
setenv = 
	PIP_EXTRA_INDEX_URL = https://username:password@XXXXXXXXXXX/packages/pypi/simple
....
```
but that did not help. The warning is still there and the packages are not installed.

**Comment by enpaul** [comment]
Hi @aha79 so sorry about the delay in dealing with this. If you're still encountering this problem, could you please share the verbose log output from a tox run where you encounter this error? You can run `tox -vvv` to get the verbose output

**Comment by enpaul** [comment]
@aha79 I'm going to close this due to inactivity. However if you encounter this again or have additional information please feel free to re-open this issue.
