### ISSUE TITLE
Request: Recommend users to explicitly depend on poetry instead of `[poetry]` extra

### ISSUE THREAD

**Issue by brandon-leapyear** [enpaul/tox-poetry-installer#79]
When we upgraded our codebase to use Poetry 1.3, we updated all our lockfiles with `--no-update`. But because `tox-poetry-installer[poetry]` adds an upper bound on `cleo < 2.0.0` (which conflicts with `poetry` 1.3.1's `cleo >= 2.0.0` dependency), `tox-poetry-installer` wasn't using the same version of Poetry. Luckily, Poetry 1.2.2 is forwards compatible with the new lock file, but we might not be so lucky in the future. When Poetry 2.0.0 is released, I wouldn't be surprised if this happens again: `tox-poetry-installer[poetry]` has `poetry < 2.0.0`, so `tox-poetry-installer` will be using a different version of poetry than the one being used on the command line.

But on a higher level, it's not immediately obvious that upgrading Poetry on the command line requires you to upgrade all the deps in your lock file (since it's not currently possible to upgrade a single transitive dependency in poetry: https://github.com/python-poetry/poetry/issues/4991). Whereas if I had `poetry` as an explicit dep in `pyproject.toml` it's 1) obvious that I need to update it, and 2) easy to update that one dependency.

IMO I think the following makes sense for `tox-poetry-installer`:
1. Have the installation instructions mention to add `poetry` as a dependency in addition to `tox-poetry-installer`
    * Since Poetry's [official installation instructions](https://python-poetry.org/docs/#installation) put Poetry in a separate virtual environment, I don't think `tox-poetry-installer` should care about the use case of someone having the Poetry CLI installed in the same environment, as documented here: https://github.com/enpaul/tox-poetry-installer/blob/4c609770f1435c6286df68e20cf48d6a65c08986/tox_poetry_installer/_poetry.py#L3-L5
2. Remove `[poetry]` extra and do one of the following:
    * Just make `poetry`/`cleo` normal deps of `tox-poetry-installer`
        * This way, if Poetry 2.0.0 comes out and the user updates their `pyproject.toml` to use `poetry = "2.0.0"`, `poetry lock` will error saying the `poetry` requested by user and the `poetry` depended on by `tox-poetry-installer` conflict, which is a **good thing** because the user is made aware that `tox-poetry-installer` (might) not work with the new version of Poetry
    * Make `poetry`/`cleo` deps with any `*` version allowed
        * This way, new Poetry/cleo versions with _just work_ if they don't touch the few things `tox-poetry-installer` needs
        * If Poetry/cleo makes changes that would actually break `tox-poetry-installer`, then `tox-poetry-installer` would need to make a new release for the fix, which would need to happen anyway even if `tox-poetry-installer` had an upper bound
    * Remove `poetry`/`cleo` deps altogether
        * Effectively the same as making the constraint `*`
        * The advantage of this approach is that if the user forgets to add `poetry` to `pyproject.toml`, `tox-poetry-installer` can show a nice "Please add `poetry` to `pyproject.toml`" error instead of implicitly using the newest version of poetry which may or may not align with the user's version of Poetry

**Comment by oshmoun** [comment]
I'm failing to see how either of the first two suggestions would have helped in the scenario you have described. You'd have still ended up with 1.2.2 due to the constraints, right?
If the above is true, then it seems like only the last suggestion is a viable approach. Could then move poetry/cleo to dev dependencies.

**Comment by brandon-leapyear** [comment]
:sparkles: _**This is an old work account. Please reference @brandonchinn178 for all future communication**_ :sparkles:


---

First of all, both of these options are assuming the first recommendation is applied, namely that the user should include `poetry` as an explicit dependency in `pyproject.toml`, alongside `tox-poetry-installer`. Doing this makes it clear that I need to bump Poetry, which isn't clear with the current `[poetry]` extra.

So regardless what we do here, the Poetry version should be explicit in `pyproject.toml`, making it more visible so that it can get bumped when upgrading Poetry in the codebase. In this situation, Poetry 1.3 would be installed; the only thing these options differ in is how to ensure `tox-poetry-installer` works with the new version of Poetry.

### Option 1: Just make `poetry`/`cleo` normal deps of `tox-poetry-installer`

In this scenario, `tox-poetry-installer` would say something like `poetry < 1.3, cleo < 2` and the user would have `poetry == 1.2.2, tox-poetry-installer == 0.10`. If this were the case when Poetry released 1.3, then updating `pyproject.toml` to say `poetry == 1.3.0, tox-poetry-installer == 0.10` would throw an error saying "conflict: your project wants 1.3.0, tox-poetry-installer wants 1.2.2".

This would give me immediate signal to come here and write an issue "Make tox-poetry-installer support Poetry 1.3" (which could be as easy as bumping the upper bound, if tox-poetry-installer doesn't depend on any features that were changed between 1.2 and 1.3).

Whereas what actually happened was my PR was merged, and things started breaking (which wasn't caught in CI because we don't run the project using `tox-poetry-installer` often).

### Option 2: Make `poetry`/`cleo` deps with any `*` version allowed

The only difference between this option and the previous option is if tox-poetry-installer Just Works with Poetry 1.3, you wouldn't need to do anything. In other words,
* Poetry makes breaking change:
    * Option 1: user gets immediate feedback that tox-poetry-installer won't work
    * Option 2: user won't know until running tox-poetry-installer
* Poetry doesn't break anything tox-poetry-installer cares about:
    * Option 1: user gets false negative, maintainer has to release new version with support for new bounds
    * Option 2: Just Works

Or, even simpler, Option 1 prevents false positives, Option 2 prevents false negatives.

**Comment by oshmoun** [comment]
> First of all, both of these options are assuming the first recommendation is applied, namely that the user should include `poetry` as an explicit dependency in `pyproject.toml`, alongside `tox-poetry-installer`. Doing this makes it clear that I need to bump Poetry, which isn't clear with the current `[poetry]` extra.

Thanks for the explanation :smile: 

Though my opinion matters little, as it's not my decision to make, but I'd prefer option 1. Having poetry as an explicitly constrained dependency, and only needing small version bumps when a new (non-breaking) version is released sounds like the safest option to avoid scenarios like the one you described.
