### ISSUE TITLE
ERROR: Error creating virtualenv. Note that spaces in paths are not supported by virtualenv. Error details: FileNotFoundError(2, 'No such file or directory')

### ISSUE THREAD

**Issue by iurisilvio** [enpaul/tox-poetry-installer#81]
I tried to use the lib for the first time and failed. 😞 Maybe I'm doing something wrong, so I reproduced it in a small project. https://github.com/iurisilvio/test-tox-poetry-installer

It is a clean poetry project (generated with `poetry new`), added only [tox.ini](https://github.com/iurisilvio/test-tox-poetry-installer/blob/35696541c1551ce80f84167b4e2b44f6aee63fc1/tox.ini) and [.github/workflows/python-package.yml](https://github.com/iurisilvio/test-tox-poetry-installer/blob/35696541c1551ce80f84167b4e2b44f6aee63fc1/.github/workflows/python-package.yml) files.

Here are log files for one failing build: [test-tox-poetry-installer.txt](https://github.com/enpaul/tox-poetry-installer/files/10402896/test-tox-poetry-installer.txt)

**Comment by enpaul** [comment]
Hi @iurisilvio , thank you very much for the bug report, and sorry for the delay in response here. Could you please share what version of Tox you're using and potentially try with the newer 1.0.0b1 release?

**Comment by iurisilvio** [comment]
Hi @enpaul, I don't remember much about this issue, but I ran my example project again:

v0.10.3: https://github.com/iurisilvio/test-tox-poetry-installer/actions/runs/10377724847/job/28732533597
v1.0.0b1: https://github.com/iurisilvio/test-tox-poetry-installer/actions/runs/10377773049/job/28732686831

v1 failed different, because I don't have a poetry.lock file.

**Comment by enpaul** [comment]
Ahh I think I see the issue here. This is actually the same error, but the latter is more descriptive. In both cases, the attempt to find `poetry.lock` raises a `FileNotFoundError`. I can handle that more gracefully internally.
