### ISSUE TITLE
Packages with missing and unbuildable wheels silently not installed when `skipsdist=true` is set

### ISSUE THREAD

**Issue by benbariteau** [enpaul/tox-poetry-installer#86]
When `skipsdist = true` is set in `tox.ini` and one of the required packages is missing a wheel and that wheel can't be built on the spot, it just silently doesn't get installed.

One curious thing is that this can be partially fixed while keeping `skipsdist = true` by doing `tox --parallel-install-threads 0`, which causes tox to print out a success message, but then subsequently print out the failed wheel build's log and return 1 as the exitcode.

Here's a minimal reproduction I created: https://github.com/benbariteau/tox-poetry-installer-parallel-install-bug-repro

**Comment by benbariteau** [comment]
I realize that since the fix here is simple (remove `skipsdist = true`) there's no good reason to fix this, but since it bit me at least having this bug around will save someone else some time.

**Comment by oshmoun** [comment]
does this happen if the faulty package is added as a normal tox dependency to the testenv?

**Comment by benbariteau** [comment]
If I understand what you're asking correctly, if I create an effectively equivalent vanilla tox setup:
```
[tox]
envlist = py39, py310
skipsdist = true

[testenv]
deps =
    greenlet==1.0.0
```

I get an error during the `py310` build about it being unable to build the wheel, as I would want and expect in this case.

**Comment by enpaul** [comment]
I think this is likely an issue with how we're doing multithreading. My hunch is that the exit code from the multithreaded process gets swallowed by the parent process, causing the parent process to ignore any non-zero exit codes. This is based on the description of `--parallel-install-threads=0` solving the problem: when the threads is 0 multithreading is bypassed entirely, thus the failing exit code would originate from the parent process and correctly cause an install failure.

**Comment by benbariteau** [comment]
Yeah I poked through this code and I noticed that none of the futures here: https://github.com/enpaul/tox-poetry-installer/blob/devel/tox_poetry_installer/installer.py#L78 ever get their result method called, which is what would raise an exception of an error occurred. I don't know why this is only a problem when using `skipsdist=true` though.
