### ISSUE TITLE
Correcting "poetry_dep_groups" vs "poetry_dev_groups"

### ISSUE THREAD

**Issue by moloney** [enpaul/tox-poetry-installer#88]
The documentation says to use "poetry_dep_groups", but this doesn't work for me.  Using "poetry_dev_groups" as mentioned in the deprecation error for "install_dev_deps" does work.

**Comment by moloney** [comment]
Whoops, I made a mistake.  Neither of the new options results in the "dev" group being installed.  Only the deprecated "install_dev_deps" actually works.

**Comment by enpaul** [comment]
Hi @moloney thanks for your issue!

There are two different options you're referring to here:

* `poetry_dep_groups` specifies a list of dependency groups from the `tool.poetry.group` section of `pyproject.toml` to install to the tox environment
* `install_dev_deps` specifically installs dependencies from the `tool.poetry.group.dev` section of `pyproject.toml` to the tox environment. As you note, this option is also deprecated.

The usage of these two options shown below are functionally identical:
```
# supported
[testenv]
poetry_dep_groups =
    dev

# deprecated
[testenv]
install_dev_deps = true
```

**Comment by moloney** [comment]
I spent some more time testing this.  Setting it as a one liner "poetry_dep_groups = [dev]" as mentioned in the README doesn't work.  Setting it using the multiline construction in your comment does work.

In addition the deprecation warning for "install_dev_deps" has a typo where it says to use "poetry_dev_groups", and it also uses the single line construction which currently doesn't work.

**Comment by enpaul** [comment]
Ah good catches. Not sure why the single-line feature isn't working, that might be how Tox is parsing it. Either way though it's a bug for the docs and deprecation notice to suggest incorrect syntax

**Comment by enpaul** [comment]
Fixed with the removal of the deprecated features (and README correction) in 1.0.0b1
