### ISSUE TITLE
Support poetry 1.5.0+

### ISSUE THREAD

**Issue by Mause** [enpaul/tox-poetry-installer#89]
The `PipInstaller` class that tox-poetry-installer uses was deprecated in 1.4.0, and has been removed in 1.5.0

See https://github.com/python-poetry/poetry/pull/7356

**Comment by oshmoun** [comment]
working on it in #80

**Comment by enpaul** [comment]
@Mause the [new beta release](https://github.com/enpaul/tox-poetry-installer/releases/tag/1.0.0b1) should offer compatibility with poetry 1.5, could you try it out and report any bugs you encounter?

**Comment by Mause** [comment]
Looks good! See https://github.com/Mause/duckdb_engine/pull/747 & https://github.com/Mause/duckdb_engine/pull/746

**Comment by oshmoun** [comment]
Can also confirm that the pre-release works fine with poetry 1.6.1

**Comment by enpaul** [comment]
Closed with 1.0.0b1
